### ISSUE TITLE
Render the popup content somewhere other than a popup

### ISSUE THREAD

**Issue by chrislkeller** [chrislkeller/new-mexico-grab-and-go-meal-pickups-for-parents#2]
It's hard to click markers. Is there a distance we can use based on the user search that shows details from the closest point?

**Comment by chrislkeller** [comment]
* [Idea](https://www.ajc.com/news/state--regional-govt--politics/how-metro-atlanta-precincts-voted-the-2018-georgia-gubernatorial-election/laukDFmDv2040jFzoaGQjK/) from the Atlanta Journal Constitution
* [Idea](https://raw.githubusercontent.com/chrislkeller/covid19-testing/master/TestSiteLocator.png) from Jared Kushner's younger brother Joshua's firm

**Comment by russbiggs** [comment]
@chrislkeller is the AJC anything different from a popup but on hover? I like the side table on the Kushner app, I wonder how we could achieve something like that on mobile with the limited real estate.  I have a branch right now doing some layout changes I cna try to implement one of these on that and share some screenshots.

**Comment by chrislkeller** [comment]
@russbiggs - If you drop the AJC map down to a mobile viewport it sticks to the bottom on hover. Now I'm not advocating hover necessarily, but anchoring the info somewhere I think is better for the user?

**Comment by russbiggs** [comment]
Got it! yeah that is nice.  We could implement both methods, one for desktop and one for mobile.  I mocked up some quick examples:

Mobile:

![mobile](https://user-images.githubusercontent.com/8487728/78191779-f6251180-7433-11ea-9452-00a32437aed0.png)


Desktop:

![fullscreen](https://user-images.githubusercontent.com/8487728/78191784-f9200200-7433-11ea-8edf-f6ef23168f10.png)

**Comment by chrislkeller** [comment]
I like the approach... I think it's a good balance right and gives the information some room to breathe?
