### ISSUE TITLE
Map markers should help user know if it's a school or district

### ISSUE THREAD

**Issue by chrislkeller** [chrislkeller/new-mexico-grab-and-go-meal-pickups-for-parents#6]
Something as simple as a color distinction would help I think.

**Comment by russbiggs** [comment]
I've seen some other maps that have a similar functionality and I liked the use of icons for markers.  Something simple like this for school:

![noun_School_1443075](https://user-images.githubusercontent.com/8487728/79058342-fee2c800-7c29-11ea-944f-d24895ccc306.png)

Not totally sure how we could display district, maybe a couple of schools in the marker?

**Comment by chrislkeller** [comment]
If that exists as a SVG I could probably arrange like three of em ...

Maybe make the background a little different color?
